name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # ✅ updated from v2 to v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # ✅ updated from v1 to v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # ✅ updated from v2 to v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5  # ✅ updated from v2 to v5
        with:
          context: .
          push: true
          tags: mrshah8218/fastapi-cicd:latest
#gfjkrsfbnglsdfhngfljsdbnvljsdbnlgfbnvsdljbgvlbj
