name: CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: mrshah8218/fastapi-cicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and test Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:local-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test the built image
        run: |
          # Build the image separately for testing
          docker build -t local-test .
          # Run the container
          docker run -d --name test-container -p 8000:8000 local-test
          sleep 5
          curl --fail http://localhost:8000
          docker stop test-container
          docker rm test-container

      - name: Push to Docker Hub
        if: success()  # Only push if previous steps succeeded
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max